# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["kblanks@fastly.com"]
description = "Park your users in a virtual queue to reduce the demand on your origins during peak times."
language = "javascript"
manifest_version = 2
name = "compute-starter-kit-javascript-queue"
service_id = "2m8R5zIahiGBdKTfYv8k8L"

[local_server]

  [local_server.backends]

    [local_server.backends.protected_content]
    url = "https://eventworld-static.s3.eu-west-2.amazonaws.com"
    override_host = "eventworld-static.s3.eu-west-2.amazonaws.com"

    [local_server.backends.upstash]
    url = "https://eu1-close-treefrog-37046.upstash.io"
    override_host = "eu1-close-treefrog-37046.upstash.io"

  [local_server.dictionaries]

    [local_server.dictionaries.config]

      format = "inline-toml"

      [local_server.dictionaries.config.contents]
      upstash_url = "https://eu1-close-treefrog-37046.upstash.io/"
      upstash_token = "AZC2ASQgYjkwNjY3MGUtYjM5NS00MmE5LTk1ZDctMmIxYzU4Y2E0ZTAyMmI1ODAxMTEzMTQ2NDY1YmJhYzI0YTc1MjhjMjEwY2Q="
      jwt_secret = "abc123"
